# Generated by Django 5.1.15 on 2026-04-26 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ledgerentry',
            options={'ordering': ['-created_at']},
        ),
    ]
