# Generated by Django 5.1.15 on 2026-04-26 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0002_payoutauditlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payout',
            options={'ordering': ['-created_at']},
        ),
    ]
